# Generated by Django 3.2.15 on 2022-10-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
    ]
